"""
Module providing typed dicts for the metadata ControllerMeta:
- pest/metadata/types/controller_meta.py

ATTENTION:
This file was auto-generated by tools/generator.py.
Do not edit manually.
"""

from enum import Enum
from typing import Any, Callable, Sequence, TypedDict


class ControllerMetaDict(TypedDict, total=False):
    tags: list[str | Enum] | None
    redirect_slashes: bool | None
    on_startup: Sequence[Callable[[], Any]] | None
    on_shutdown: Sequence[Callable[[], Any]] | None
    deprecated: bool | None
    include_in_schema: bool | None
