"""
Module providing typed dicts for the metadata ModuleMeta:
- pest/metadata/types/module_meta.py

ATTENTION:
This file was auto-generated by tools/generator.py.
Do not edit manually.
"""

from typing import TypedDict

from ...metadata.types.module_meta import InjectionToken, Provider
from ...primitives.controller import Controller


class ModuleMetaDict(TypedDict, total=False):
    imports: list[type] | None
    providers: list[Provider] | None
    exports: list[InjectionToken] | None
    controllers: list[type[Controller]] | None
