name: "🔖 » draft release"
on:
  workflow_call:
  workflow_dispatch:

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: 'bash'

jobs:
  release:
    name: "🔖 » draft release"
    runs-on: ubuntu-latest
    outputs:
      release-note: ${{ steps.changelog.outputs.changelog }}
      version: ${{ steps.version.outputs.local-version }}

    steps:
      - name: 📁 » checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ⬅️ » get previous git tag
        id: tag
        run: echo "last-tag=$(git describe --tags --abbrev=0 || git rev-list --max-parents=0 ${{github.ref}})" >> $GITHUB_OUTPUT
      
      - name: 🏷️ » get versions
        uses: ./.github/actions/check-version
        id: version
        with:
          pyproject-path: "./pyproject.toml"

      - name: 📑 » generate changelog
        uses: lucaslabstech/action-release@eb37864cffaf83e679c8aaee07707ba71041b41f # v1.0.4
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          from: ${{ steps.tag.outputs.last-tag }}
          to: ${{ github.ref }}
          next-version: v${{ steps.version.outputs.local-version }}
          

      - name: 🗑️ » delete outdated drafts
        uses: hugo19941994/delete-draft-releases@1bdca1ea7ffb25ae7f468a7bdb40056dae98175e # v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔖 » create draft release
        uses: ncipollo/release-action@cdcc88a9acf3ca41c16c37bb7d21b9ad48560d87 # v1.15.0
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          prerelease: false
          draft: true
          tag: v${{ steps.version.outputs.local-version }}
          name: v${{ steps.version.outputs.local-version }}
          body: ${{ steps.changelog.outputs.changelog }}